[2024-07-13T15:24:10.213+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-13T15:24:10.249+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test manual__2024-07-13T15:21:44.430274+00:00 [queued]>
[2024-07-13T15:24:10.267+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test manual__2024-07-13T15:21:44.430274+00:00 [queued]>
[2024-07-13T15:24:10.267+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-13T15:24:10.293+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.dim_suppliers.test> on 2024-07-13 15:21:44.430274+00:00
[2024-07-13T15:24:10.304+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1705) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-13T15:24:10.305+0000] {standard_task_runner.py:63} INFO - Started process 1711 to run task
[2024-07-13T15:24:10.304+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_suppliers.test', 'manual__2024-07-13T15:21:44.430274+00:00', '--job-id', '445', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp4l5nmiil']
[2024-07-13T15:24:10.307+0000] {standard_task_runner.py:91} INFO - Job 445: Subtask transform.dim_suppliers.test
[2024-07-13T15:24:10.331+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-13T15:24:10.390+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_suppliers.test manual__2024-07-13T15:21:44.430274+00:00 [running]> on host airflow-scheduler
[2024-07-13T15:24:10.567+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_suppliers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-13T15:21:44.430274+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-13T15:21:44.430274+00:00'
[2024-07-13T15:24:10.570+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-13T15:24:10.572+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-13T15:24:10.574+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpq6qa1xsk from /opt/airflow/dags/dbt/dbt_project
[2024-07-13T15:24:10.584+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-13T15:24:10.623+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-13T15:24:10.624+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-13T15:24:10.625+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-13T15:24:10.628+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-13T15:24:10.629+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpq6qa1xsk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpq6qa1xsk
[2024-07-13T15:24:10.630+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-13T15:24:10.632+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpq6qa1xsk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-13T15:24:10.646+0000] {subprocess.py:84} INFO - Command output:
[2024-07-13T15:24:14.008+0000] {subprocess.py:94} INFO - [0m15:24:14  Running with dbt=1.8.3
[2024-07-13T15:24:14.404+0000] {subprocess.py:94} INFO - [0m15:24:14  Updating lock file in file path: /tmp/tmpq6qa1xsk/package-lock.yml
[2024-07-13T15:24:14.415+0000] {subprocess.py:94} INFO - [0m15:24:14  Installing dbt-labs/dbt_utils
[2024-07-13T15:24:14.903+0000] {subprocess.py:94} INFO - [0m15:24:14  Installed from version 0.8.6
[2024-07-13T15:24:14.905+0000] {subprocess.py:94} INFO - [0m15:24:14  Updated version available: 1.2.0
[2024-07-13T15:24:14.908+0000] {subprocess.py:94} INFO - [0m15:24:14
[2024-07-13T15:24:14.912+0000] {subprocess.py:94} INFO - [0m15:24:14  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-13T15:24:14.914+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-13T15:24:16.419+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-13T15:24:16.420+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-13T15:24:16.421+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmpq6qa1xsk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpq6qa1xsk
[2024-07-13T15:24:16.423+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-13T15:24:16.425+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmpq6qa1xsk', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-13T15:24:16.440+0000] {subprocess.py:84} INFO - Command output:
[2024-07-13T15:24:20.649+0000] {subprocess.py:94} INFO - [0m15:24:20  Running with dbt=1.8.3
[2024-07-13T15:24:21.947+0000] {subprocess.py:94} INFO - [0m15:24:21  Registered adapter: snowflake=1.8.3
[2024-07-13T15:24:24.000+0000] {subprocess.py:94} INFO - [0m15:24:24  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-13T15:24:24.004+0000] {subprocess.py:94} INFO - [0m15:24:24
[2024-07-13T15:24:29.147+0000] {subprocess.py:94} INFO - [0m15:24:29  Concurrency: 1 threads (target='dev')
[2024-07-13T15:24:29.149+0000] {subprocess.py:94} INFO - [0m15:24:29
[2024-07-13T15:24:29.164+0000] {subprocess.py:94} INFO - [0m15:24:29  1 of 1 START test not_null_dim_suppliers_SUPPLIERID ............................ [RUN]
[2024-07-13T15:24:31.532+0000] {subprocess.py:94} INFO - [0m15:24:31  1 of 1 PASS not_null_dim_suppliers_SUPPLIERID .................................. [[32mPASS[0m in 2.37s]
[2024-07-13T15:24:31.541+0000] {subprocess.py:94} INFO - [0m15:24:31
[2024-07-13T15:24:31.543+0000] {subprocess.py:94} INFO - [0m15:24:31  Finished running 1 test in 0 hours 0 minutes and 7.54 seconds (7.54s).
[2024-07-13T15:24:31.723+0000] {subprocess.py:94} INFO - [0m15:24:31
[2024-07-13T15:24:31.724+0000] {subprocess.py:94} INFO - [0m15:24:31  [32mCompleted successfully[0m
[2024-07-13T15:24:31.725+0000] {subprocess.py:94} INFO - [0m15:24:31
[2024-07-13T15:24:31.727+0000] {subprocess.py:94} INFO - [0m15:24:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-13T15:24:33.545+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-13T15:24:33.547+0000] {local.py:254} INFO - [0m15:24:31  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-13T15:24:33.777+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-13T15:24:33.778+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-13T15:24:33.785+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None)]
[2024-07-13T15:24:33.787+0000] {local.py:350} INFO - Outlets: []
[2024-07-13T15:24:33.788+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-13T15:24:33.813+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-07-13T15:24:33.861+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-13T15:24:33.897+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_suppliers.test, run_id=manual__2024-07-13T15:21:44.430274+00:00, execution_date=20240713T152144, start_date=20240713T152410, end_date=20240713T152433
[2024-07-13T15:24:33.930+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-13T15:24:33.989+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-13T15:24:33.993+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
