[2024-06-27T14:41:55.107+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-27T14:41:55.241+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: TEST_SPARK.extract.extract_suppliers manual__2024-06-27T14:41:49.822590+00:00 [queued]>
[2024-06-27T14:41:55.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: TEST_SPARK.extract.extract_suppliers manual__2024-06-27T14:41:49.822590+00:00 [queued]>
[2024-06-27T14:41:55.491+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-27T14:41:55.647+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): extract.extract_suppliers> on 2024-06-27 14:41:49.822590+00:00
[2024-06-27T14:41:55.748+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2049) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-27T14:41:55.758+0000] {standard_task_runner.py:63} INFO - Started process 2063 to run task
[2024-06-27T14:41:55.737+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'TEST_SPARK', 'extract.extract_suppliers', 'manual__2024-06-27T14:41:49.822590+00:00', '--job-id', '408', '--raw', '--subdir', 'DAGS_FOLDER/elt-spark.py', '--cfg-path', '/tmp/tmpja20pr_a']
[2024-06-27T14:41:55.764+0000] {standard_task_runner.py:91} INFO - Job 408: Subtask extract.extract_suppliers
[2024-06-27T14:41:55.897+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-27T14:41:56.441+0000] {task_command.py:426} INFO - Running <TaskInstance: TEST_SPARK.extract.extract_suppliers manual__2024-06-27T14:41:49.822590+00:00 [running]> on host airflow-scheduler
[2024-06-27T14:41:57.178+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='TEST_SPARK' AIRFLOW_CTX_TASK_ID='extract.extract_suppliers' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T14:41:49.822590+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-27T14:41:49.822590+00:00'
[2024-06-27T14:41:57.190+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-27T14:41:57.192+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-27T14:41:57.195+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt-spark.py", line 41, in extract_task
    return extract_func(
           ^^^^^^^^^^^^^
  File "/opt/airflow/dags/spark/extractors.py", line 11, in extract_func
    JDBC_CONN = f'jdbc:postgresql://{HOST}/{DB_NAME}'
                                            ^^^^^^^
NameError: name 'DB_NAME' is not defined
[2024-06-27T14:41:57.329+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=TEST_SPARK, task_id=extract.extract_suppliers, run_id=manual__2024-06-27T14:41:49.822590+00:00, execution_date=20240627T144149, start_date=20240627T144155, end_date=20240627T144157
[2024-06-27T14:41:57.421+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 408 for task extract.extract_suppliers (name 'DB_NAME' is not defined; 2063)
[2024-06-27T14:41:57.489+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-27T14:41:57.624+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-27T14:41:57.641+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
