[2024-07-14T03:50:01.613+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T03:50:01.661+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test manual__2024-07-14T03:47:05.410676+00:00 [queued]>
[2024-07-14T03:50:01.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.dim_suppliers.test manual__2024-07-14T03:47:05.410676+00:00 [queued]>
[2024-07-14T03:50:01.689+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T03:50:01.721+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.dim_suppliers.test> on 2024-07-14 03:47:05.410676+00:00
[2024-07-14T03:50:01.736+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=8983) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T03:50:01.739+0000] {standard_task_runner.py:63} INFO - Started process 8998 to run task
[2024-07-14T03:50:01.736+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.dim_suppliers.test', 'manual__2024-07-14T03:47:05.410676+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpw_ggox5i']
[2024-07-14T03:50:01.741+0000] {standard_task_runner.py:91} INFO - Job 659: Subtask transform.dim_suppliers.test
[2024-07-14T03:50:01.778+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T03:50:01.857+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.dim_suppliers.test manual__2024-07-14T03:47:05.410676+00:00 [running]> on host airflow-scheduler
[2024-07-14T03:50:02.074+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.dim_suppliers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T03:47:05.410676+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T03:47:05.410676+00:00'
[2024-07-14T03:50:02.078+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T03:50:02.082+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T03:50:02.085+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp5sgzg26m from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T03:50:02.097+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T03:50:02.488+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T03:50:02.490+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T03:50:02.492+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T03:50:02.497+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T03:50:02.499+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp5sgzg26m', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp5sgzg26m
[2024-07-14T03:50:02.502+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T03:50:02.505+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp5sgzg26m', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T03:50:02.531+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T03:50:07.550+0000] {subprocess.py:94} INFO - [0m03:50:07  Running with dbt=1.8.3
[2024-07-14T03:50:08.234+0000] {subprocess.py:94} INFO - [0m03:50:08  Updating lock file in file path: /tmp/tmp5sgzg26m/package-lock.yml
[2024-07-14T03:50:08.277+0000] {subprocess.py:94} INFO - [0m03:50:08  Installing dbt-labs/dbt_utils
[2024-07-14T03:50:09.002+0000] {subprocess.py:94} INFO - [0m03:50:09  Installed from version 0.8.6
[2024-07-14T03:50:09.009+0000] {subprocess.py:94} INFO - [0m03:50:09  Updated version available: 1.2.0
[2024-07-14T03:50:09.014+0000] {subprocess.py:94} INFO - [0m03:50:09
[2024-07-14T03:50:09.020+0000] {subprocess.py:94} INFO - [0m03:50:09  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T03:50:09.025+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T03:50:11.192+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T03:50:11.194+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T03:50:11.196+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmp5sgzg26m', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp5sgzg26m
[2024-07-14T03:50:11.198+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T03:50:11.200+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'dim_suppliers', '--project-dir', '/tmp/tmp5sgzg26m', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T03:50:11.222+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T03:50:16.350+0000] {subprocess.py:94} INFO - [0m03:50:16  Running with dbt=1.8.3
[2024-07-14T03:50:17.453+0000] {subprocess.py:94} INFO - [0m03:50:17  Registered adapter: snowflake=1.8.3
[2024-07-14T03:50:19.440+0000] {subprocess.py:94} INFO - [0m03:50:19  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T03:50:19.453+0000] {subprocess.py:94} INFO - [0m03:50:19
[2024-07-14T03:50:25.292+0000] {subprocess.py:94} INFO - [0m03:50:25  Concurrency: 1 threads (target='dev')
[2024-07-14T03:50:25.301+0000] {subprocess.py:94} INFO - [0m03:50:25
[2024-07-14T03:50:25.376+0000] {subprocess.py:94} INFO - [0m03:50:25  1 of 1 START test not_null_dim_suppliers_SUPPLIERID ............................ [RUN]
[2024-07-14T03:50:27.794+0000] {subprocess.py:94} INFO - [0m03:50:27  1 of 1 PASS not_null_dim_suppliers_SUPPLIERID .................................. [[32mPASS[0m in 2.40s]
[2024-07-14T03:50:27.819+0000] {subprocess.py:94} INFO - [0m03:50:27
[2024-07-14T03:50:27.824+0000] {subprocess.py:94} INFO - [0m03:50:27  Finished running 1 test in 0 hours 0 minutes and 8.36 seconds (8.36s).
[2024-07-14T03:50:28.223+0000] {subprocess.py:94} INFO - [0m03:50:28
[2024-07-14T03:50:28.225+0000] {subprocess.py:94} INFO - [0m03:50:28  [32mCompleted successfully[0m
[2024-07-14T03:50:28.227+0000] {subprocess.py:94} INFO - [0m03:50:28
[2024-07-14T03:50:28.230+0000] {subprocess.py:94} INFO - [0m03:50:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T03:50:30.071+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T03:50:30.075+0000] {local.py:254} INFO - [0m03:50:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T03:50:30.136+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T03:50:30.138+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T03:50:30.155+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.dwh.dim_suppliers', extra=None)]
[2024-07-14T03:50:30.159+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T03:50:30.162+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T03:50:30.239+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-07-14T03:50:30.355+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T03:50:30.494+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.dim_suppliers.test, run_id=manual__2024-07-14T03:47:05.410676+00:00, execution_date=20240714T034705, start_date=20240714T035001, end_date=20240714T035030
[2024-07-14T03:50:30.616+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T03:50:30.865+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T03:50:30.876+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
