[2024-07-14T04:38:31.924+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:38:32.187+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_shippers.test scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-07-14T04:38:32.277+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_shippers.test scheduled__2024-06-27T00:00:00+00:00 [queued]>
[2024-07-14T04:38:32.278+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:38:32.899+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_shippers.test> on 2024-06-27 00:00:00+00:00
[2024-07-14T04:38:32.925+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_shippers.test', 'scheduled__2024-06-27T00:00:00+00:00', '--job-id', '1494', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp7hyxo4qz']
[2024-07-14T04:38:32.932+0000] {standard_task_runner.py:91} INFO - Job 1494: Subtask transform.raw_shippers.test
[2024-07-14T04:38:32.948+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=19801) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-14T04:38:32.959+0000] {standard_task_runner.py:63} INFO - Started process 19817 to run task
[2024-07-14T04:38:33.067+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-07-14T04:38:33.363+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_shippers.test scheduled__2024-06-27T00:00:00+00:00 [running]> on host airflow-scheduler
[2024-07-14T04:38:34.066+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_shippers.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-27T00:00:00+00:00'
[2024-07-14T04:38:34.076+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:38:34.100+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-07-14T04:38:34.104+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpmbw92d02 from /opt/airflow/dags/dbt/dbt_project
[2024-07-14T04:38:34.120+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-07-14T04:38:34.264+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-07-14T04:38:34.266+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-07-14T04:38:34.268+0000] {config.py:298} INFO - Profile caching is enable.
[2024-07-14T04:38:34.275+0000] {config.py:272} INFO - Profile found in cache using profile: /tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad/profiles.yml.
[2024-07-14T04:38:34.279+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpmbw92d02', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpmbw92d02
[2024-07-14T04:38:34.283+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:38:34.285+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpmbw92d02', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:38:34.364+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:38:51.381+0000] {subprocess.py:94} INFO - [0m04:38:51  Running with dbt=1.8.3
[2024-07-14T04:38:53.187+0000] {subprocess.py:94} INFO - [0m04:38:53  Updating lock file in file path: /tmp/tmpmbw92d02/package-lock.yml
[2024-07-14T04:38:53.232+0000] {subprocess.py:94} INFO - [0m04:38:53  Installing dbt-labs/dbt_utils
[2024-07-14T04:38:54.035+0000] {subprocess.py:94} INFO - [0m04:38:54  Installed from version 0.8.6
[2024-07-14T04:38:54.057+0000] {subprocess.py:94} INFO - [0m04:38:54  Updated version available: 1.2.0
[2024-07-14T04:38:54.059+0000] {subprocess.py:94} INFO - [0m04:38:54
[2024-07-14T04:38:54.061+0000] {subprocess.py:94} INFO - [0m04:38:54  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-07-14T04:38:54.063+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:38:56.149+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:38:56.152+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-07-14T04:38:56.154+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_shippers', '--project-dir', '/tmp/tmpmbw92d02', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpmbw92d02
[2024-07-14T04:38:56.166+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-07-14T04:38:56.173+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_shippers', '--project-dir', '/tmp/tmpmbw92d02', '--profiles-dir', '/tmp/cosmos/profile/a0017dab0633177292578162811b91dcb9c56d6e54017e9660056cc364a762ad', '--profile', 'dbt_project', '--target', 'dev']
[2024-07-14T04:38:56.258+0000] {subprocess.py:84} INFO - Command output:
[2024-07-14T04:39:12.334+0000] {subprocess.py:94} INFO - [0m04:39:12  Running with dbt=1.8.3
[2024-07-14T04:39:15.046+0000] {subprocess.py:94} INFO - [0m04:39:15  Registered adapter: snowflake=1.8.3
[2024-07-14T04:39:20.557+0000] {subprocess.py:94} INFO - [0m04:39:20  Found 20 models, 27 data tests, 11 sources, 684 macros
[2024-07-14T04:39:20.595+0000] {subprocess.py:94} INFO - [0m04:39:20
[2024-07-14T04:39:26.572+0000] {subprocess.py:94} INFO - [0m04:39:26  Concurrency: 1 threads (target='dev')
[2024-07-14T04:39:26.584+0000] {subprocess.py:94} INFO - [0m04:39:26
[2024-07-14T04:39:26.717+0000] {subprocess.py:94} INFO - [0m04:39:26  1 of 1 START test not_null_raw_shippers_SHIPPERID .............................. [RUN]
[2024-07-14T04:39:29.102+0000] {subprocess.py:94} INFO - [0m04:39:29  1 of 1 PASS not_null_raw_shippers_SHIPPERID .................................... [[32mPASS[0m in 2.39s]
[2024-07-14T04:39:29.154+0000] {subprocess.py:94} INFO - [0m04:39:29
[2024-07-14T04:39:29.170+0000] {subprocess.py:94} INFO - [0m04:39:29  Finished running 1 test in 0 hours 0 minutes and 8.56 seconds (8.56s).
[2024-07-14T04:39:30.073+0000] {subprocess.py:94} INFO - [0m04:39:30
[2024-07-14T04:39:30.081+0000] {subprocess.py:94} INFO - [0m04:39:30  [32mCompleted successfully[0m
[2024-07-14T04:39:30.088+0000] {subprocess.py:94} INFO - [0m04:39:30
[2024-07-14T04:39:30.104+0000] {subprocess.py:94} INFO - [0m04:39:30  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:39:33.070+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-07-14T04:39:33.073+0000] {local.py:254} INFO - [0m04:39:30  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-07-14T04:39:34.126+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-07-14T04:39:34.127+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-07-14T04:39:34.149+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://OU00370.europe-west2.gcp/ELT_BATCH.raw.raw_shippers', extra=None)]
[2024-07-14T04:39:34.203+0000] {local.py:350} INFO - Outlets: []
[2024-07-14T04:39:34.207+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-07-14T04:39:34.691+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:39:34.899+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_shippers.test, run_id=scheduled__2024-06-27T00:00:00+00:00, execution_date=20240627T000000, start_date=20240714T043832, end_date=20240714T043934
[2024-07-14T04:39:35.426+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-14T04:39:35.608+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:39:35.618+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
